# Generated by Django 5.0.3 on 2024-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('program_name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('things_needed', models.TextField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
